package repository

import (
	"context"
	"database/sql"
	"time"

	"closet-backend/internal/models"
)

type ItemRepository interface {
	Create(ctx context.Context, it *models.Item) error
	FindByID(ctx context.Context, id string) (*models.Item, error)
	// List returns a page of items for a user, optionally filtered by
	// category, plus the total count for pagination metadata.
	List(ctx context.Context, userID, category string, page, perPage int) ([]models.Item, int, error)
	Update(ctx context.Context, id string, fields map[string]interface{}) error
	Delete(ctx context.Context, id string) error
	LogWear(ctx context.Context, id string) error
	History(ctx context.Context, userID string, limit int) ([]models.WearLogEntry, error)
}

type itemRepository struct {
	db      *sql.DB
	timeout time.Duration
}

func NewItemRepository(db *sql.DB, timeout time.Duration) ItemRepository {
	return &itemRepository{db: db, timeout: timeout}
}

func (r *itemRepository) Create(ctx context.Context, it *models.Item) error {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	// it.ID is generated by the caller (service layer) rather than left to
	// the database's gen_random_uuid() default — Phase 3 needs the item ID
	// before the row exists, to build the image storage key
	// (users/{userID}/items/{itemID}/...) and store the file before the
	// insert happens. See service.ItemService.Create.
	row := r.db.QueryRowContext(ctx, `
		INSERT INTO items (
			id, user_id, category, name, brand, price, purchase_date, expiry_date,
			consumable, inventory_percent, times_used, status, notes, color, photo,
			worn, favorite, fit, season, occasion, material, size, shade, finish,
			subtype, card_style,
			image_url, thumbnail_url, image_mime_type, image_file_size,
			image_width, image_height, image_storage_key, thumbnail_storage_key, image_uploaded_at,
			pattern_url, pattern_scale, pattern_offset_x, pattern_offset_y, pattern_rotation, pattern_tint
		) VALUES ($1,$2,$3,$4,$5,$6, NULLIF($7,'')::date, NULLIF($8,'')::date,
			$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,
			$27,$28,$29,$30,$31,$32,$33,$34,$35,
			$36,$37,$38,$39,$40,$41)
		RETURNING created_at, updated_at`,
		it.ID, it.UserID, it.Category, it.Name, it.Brand, it.Price, deref(it.PurchaseDate), deref(it.ExpiryDate),
		it.Consumable, it.InventoryPercent, it.TimesUsed, it.Status, it.Notes, it.Color, it.Photo,
		it.Worn, it.Favorite, it.Fit, it.Season, it.Occasion, it.Material, it.Size, it.Shade, it.Finish,
		it.Subtype, it.CardStyle,
		it.ImageURL, it.ThumbnailURL, it.ImageMimeType, it.ImageFileSize,
		it.ImageWidth, it.ImageHeight, it.ImageStorageKey, it.ThumbnailStorageKey, it.ImageUploadedAt,
		it.PatternURL, it.PatternScale, it.PatternOffsetX, it.PatternOffsetY, it.PatternRotation, it.PatternTint,
	)
	return row.Scan(&it.CreatedAt, &it.UpdatedAt)
}

func (r *itemRepository) FindByID(ctx context.Context, id string) (*models.Item, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	it := &models.Item{}
	err := r.db.QueryRowContext(ctx, itemSelectCols+` FROM items WHERE id = $1`, id).Scan(itemScanArgs(it)...)
	if err == sql.ErrNoRows {
		return nil, ErrNotFound
	}
	return it, err
}

func (r *itemRepository) List(ctx context.Context, userID, category string, page, perPage int) ([]models.Item, int, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	if page < 1 {
		page = 1
	}
	if perPage < 1 || perPage > 100 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	var total int
	var countErr error
	if category != "" {
		countErr = r.db.QueryRowContext(ctx, `SELECT count(*) FROM items WHERE user_id = $1 AND category = $2`, userID, category).Scan(&total)
	} else {
		countErr = r.db.QueryRowContext(ctx, `SELECT count(*) FROM items WHERE user_id = $1`, userID).Scan(&total)
	}
	if countErr != nil {
		return nil, 0, countErr
	}

	var rows *sql.Rows
	var err error
	if category != "" {
		rows, err = r.db.QueryContext(ctx, itemSelectCols+` FROM items WHERE user_id = $1 AND category = $2 ORDER BY created_at ASC LIMIT $3 OFFSET $4`, userID, category, perPage, offset)
	} else {
		rows, err = r.db.QueryContext(ctx, itemSelectCols+` FROM items WHERE user_id = $1 ORDER BY created_at ASC LIMIT $2 OFFSET $3`, userID, perPage, offset)
	}
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	items := []models.Item{}
	for rows.Next() {
		var it models.Item
		if err := rows.Scan(itemScanArgs(&it)...); err != nil {
			return nil, 0, err
		}
		items = append(items, it)
	}
	return items, total, rows.Err()
}

func (r *itemRepository) Update(ctx context.Context, id string, fields map[string]interface{}) error {
	if len(fields) == 0 {
		return nil
	}
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	setClauses := ""
	args := []interface{}{}
	i := 1
	for col, val := range fields {
		if setClauses != "" {
			setClauses += ", "
		}
		setClauses += col + " = $" + itoa(i)
		args = append(args, val)
		i++
	}
	setClauses += ", updated_at = now()"
	args = append(args, id)
	query := "UPDATE items SET " + setClauses + " WHERE id = $" + itoa(i)
	_, err := r.db.ExecContext(ctx, query, args...)
	return err
}

func (r *itemRepository) Delete(ctx context.Context, id string) error {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	if _, err := r.db.ExecContext(ctx, `UPDATE outfits SET item_ids = array_remove(item_ids, $1::uuid)`, id); err != nil {
		return err
	}
	_, err := r.db.ExecContext(ctx, `DELETE FROM items WHERE id = $1`, id)
	return err
}

func (r *itemRepository) LogWear(ctx context.Context, id string) error {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `UPDATE items SET worn = worn + 1, times_used = times_used + 1, updated_at = now() WHERE id = $1`, id); err != nil {
		tx.Rollback()
		return err
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO wear_log (item_id) VALUES ($1)`, id); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

func (r *itemRepository) History(ctx context.Context, userID string, limit int) ([]models.WearLogEntry, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()

	rows, err := r.db.QueryContext(ctx, `
		SELECT w.id, w.item_id, i.name, w.worn_at
		FROM wear_log w JOIN items i ON i.id = w.item_id
		WHERE i.user_id = $1 ORDER BY w.worn_at DESC LIMIT $2`, userID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []models.WearLogEntry{}
	for rows.Next() {
		var e models.WearLogEntry
		if err := rows.Scan(&e.ID, &e.ItemID, &e.ItemName, &e.WornAt); err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, rows.Err()
}

const itemSelectCols = `SELECT id, user_id, category, name, brand, price,
	purchase_date::text, expiry_date::text,
	consumable, inventory_percent, times_used, status, notes, color, photo,
	worn, favorite, fit, season, occasion, material, size, shade, finish,
	subtype, card_style,
	image_url, thumbnail_url, image_mime_type, image_file_size,
	image_width, image_height, image_storage_key, thumbnail_storage_key, image_uploaded_at,
	pattern_url, pattern_scale, pattern_offset_x, pattern_offset_y, pattern_rotation, pattern_tint,
	created_at, updated_at`

func itemScanArgs(it *models.Item) []interface{} {
	return []interface{}{
		&it.ID, &it.UserID, &it.Category, &it.Name, &it.Brand, &it.Price,
		&it.PurchaseDate, &it.ExpiryDate,
		&it.Consumable, &it.InventoryPercent, &it.TimesUsed, &it.Status, &it.Notes, &it.Color, &it.Photo,
		&it.Worn, &it.Favorite, &it.Fit, &it.Season, &it.Occasion, &it.Material, &it.Size, &it.Shade, &it.Finish,
		&it.Subtype, &it.CardStyle,
		&it.ImageURL, &it.ThumbnailURL, &it.ImageMimeType, &it.ImageFileSize,
		&it.ImageWidth, &it.ImageHeight, &it.ImageStorageKey, &it.ThumbnailStorageKey, &it.ImageUploadedAt,
		&it.PatternURL, &it.PatternScale, &it.PatternOffsetX, &it.PatternOffsetY, &it.PatternRotation, &it.PatternTint,
		&it.CreatedAt, &it.UpdatedAt,
	}
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	neg := i < 0
	if neg {
		i = -i
	}
	buf := [20]byte{}
	pos := len(buf)
	for i > 0 {
		pos--
		buf[pos] = byte('0' + i%10)
		i /= 10
	}
	if neg {
		pos--
		buf[pos] = '-'
	}
	return string(buf[pos:])
}
